language: java
dist: trusty
script: export MAVEN_OPTS="-Xmx1024m" && mvn test --quiet
addons:
  hostname: short-hostname
jdk:
  - oraclejdk8
notifications:
  email: false
after_success:
  - mvn clean cobertura:cobertura coveralls:report
